id: A8CC8ADBC
title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
type: translation
pechas:
- I633693B4
- I45999F70
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:42.799298
  last_modified_at: 2023-01-04 12:35:42.799310
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I633693B4/0591: '7490'
  I45999F70/29D0: '7490'
